
@startuml
锋利器异常考勤申诉 -> "节点审批人审批": 提交
"节点审批人审批" -> 更新考勤数据:同意
note right 节点审批人审批
审批人中有运营人员审批，
如果运营人员认为申诉的考勤工时存在问题，
会在审批的过程中进行更改
end note
note right 更新考勤数据
如果是超时申诉，
申诉的工时按照比例折扣，比例分别是 0.75， 0.5，0
夜班超时申诉扣减 直接按照申诉工时的0.5来计算
end note
@enduml